### ISSUE TITLE
Score NVSS x TGSS pairs

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#11]
Develop a function that takes an NVSS and a TGSS object and scores how related they are.

**Comment by MatthewJA** [comment]
...and then score your existing pairs.

**Comment by daccordeon** [comment]
I can do this over the patch, however, the scorers all current input a TGSS and a NVSS source.
To sort all TGSS objects, we need a scorer that returns the likelihood that a match lies in NVSS (just loop over all possible matches of the TGSS object)

**Comment by MatthewJA** [comment]
Yup, that'll work

**Comment by MatthewJA** [comment]
But scoring pairs is more interesting! At any rate, prioritise logistic regression (#20) over this.
