### ISSUE TITLE
Cross-identify TGSS and NVSS catalogues with positional matching

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#2]
1. Obtain the TGSS and NVSS catalogues.
    - TGSS: http://tgssadr.strw.leidenuniv.nl/doku.php
    - NVSS: ftp://nvss.cv.nrao.edu/pub/nvss/CATALOG/ or mirrored https://heasarc.gsfc.nasa.gov/W3Browse/all/nvss.html
2. Following Section 2.3 of https://arxiv.org/pdf/1609.01308.pdf, match TGSS and NVSS.
3. Plot a histogram of the angular separation between matches.
4. Using Equation 3 of the above paper, compute the spectral index ɑ and reproduce Figure 2.

**Comment by chengsoonong** [comment]
I wonder whether it is worth pre-filtering with a Euclidean nearest neighbour?
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree

**Comment by daccordeon** [comment]
Not quite sure what that would be Cheng, is it just for computational speed?

**Comment by MatthewJA** [comment]
Yes! KDTrees are super fast ways to do spatial look-ups. There's a few reasons you wouldn't want one for this particular cross-matching problem (I'll leave you to think about what those might be) but they'd make a great first-pass.

**Comment by daccordeon** [comment]
_(1) Obtain the TGSS and NVSS catalogues_
done! must be called CATALOG.FIT and TGSSADR1_7sigma_catalog.tsv 
_(2) Following the paper, match TGSS and NVSS_
done! see catalogue.csv
_(3)Plot a histogram of the angular separation between matches_
done! see hist_angle.png
_(4)Using Equation 3 of the above paper, compute the spectral index ɑ and reproduce Figure 2._
done! see hist_alpha.png
