### ISSUE TITLE
Implement logistic regression in pytorch

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#20]

**Comment by MatthewJA** [comment]
Train using positional matches (i.e. "is it in the match catalogue") as labels. Evaluate loss, accuracy

**Comment by daccordeon** [comment]
We're using the catalogue as our feature vectors right now, and labels are cutting off anything outside 5' (kinda). Is this what you mean?

Or should we be taking features from an extended catalogue and taking labels from a closer subset of that?

**Comment by MatthewJA** [comment]
Yup, what you're doing now is fine, as long as you have plenty of objects both above and below 5' separation.

**Comment by daccordeon** [comment]
I did this two weeks ago, more to close or extend this issue.

**Comment by daccordeon** [comment]
Hang on, logistic regression is being funny.
Prediction on features is right now only returning values between 0.15 and 0.4, as in it isn't predicting any matches at all. What's going on?

**Comment by MatthewJA** [comment]
That's fine. It could just be that there aren't any examples that produce scores below 0.15. Or perhaps you've changed your data set. Either way, don't worry about it: You can just move your threshold down (from 0.5 to, say, 0.25) and you will have more matches.

**Comment by daccordeon** [comment]
70% accuracy req

**Comment by daccordeon** [comment]
80% accuracy achieved, move to close issue!
