### ISSUE TITLE
Label some pairs

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#25]

**Comment by daccordeon** [comment]
http://tgssadr.strw.leidenuniv.nl/hips/
https://www.cv.nrao.edu/nvss/postage.shtml

TGSSADR J101822.5-270041
NVSS J101822-270043

![Screenshot from 2019-10-07 19-53-20](https://user-images.githubusercontent.com/53468019/66297878-449d9b80-e93c-11e9-86ed-efd29809eae3.png)

This looks like a match, except right now the dodgy object maker has also linked to 99 (no joke) other names into the same 'object', most of those other names are ages away.

**Comment by daccordeon** [comment]
In terms of my manual labelling, I would put this at 1.0, there's no doubt that they're the same.
Or should I be giving these cautionary 0.99's as we're 'never certain'?

**Comment by MatthewJA** [comment]
Yep, those look like a match.

> In terms of my manual labelling, I would put this at 1.0, there's no doubt that they're the same.
> Or should I be giving these cautionary 0.99's as we're 'never certain'?

Three questions:

1. Why 0.99 and not 0.999?
2. If your classifier says that a pair is 0.99, what does that mean? (How do you interpret this?)
3. What type are your labels?

(Remember the difference between labels and predictions.)

**Comment by daccordeon** [comment]
pair(S)

**Comment by MatthewJA** [comment]
This is useful too: http://alasky.u-strasbg.fr/NVSS/intensity/

**Comment by daccordeon** [comment]
Move to close this issue. I've computed the accuracy against manual labels that Matthew and I have created, see also #32 .

**Comment by MatthewJA** [comment]
What was the accuracy? And how did it compare to the accuracy on positional matching labels?
