### ISSUE TITLE
Use logistic regression scorer to partition your patch of sky into physical objects

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#31]
Each object will have some number of TGSS and NVSS components.

**Comment by MatthewJA** [comment]
Look at some of these. Are you missing components? Are you adding extras? etc

**Comment by daccordeon** [comment]
Comparison below at 5 degree fov around J101436.8-270532.
I reckon that, as expected, we're adding lots more components, especially in the central large multi-object. I will find an example where we might be missing something (like some aged triple with the two "jet-like" blobs further apart and elongated).

[torch_lr_partition.pdf](https://github.com/MatthewJA/blobmatch/files/3737769/torch_lr_partition.pdf)

![tgss_window](https://user-images.githubusercontent.com/53468019/66984869-54209f80-f107-11e9-9aa8-2f8b34bcdcec.png)
![nvss_window](https://user-images.githubusercontent.com/53468019/66984872-5551cc80-f107-11e9-9842-563af952ca34.png)

**Comment by MatthewJA** [comment]
Oh that's a super good plot. Great work!

(You're more likely to pick up too many components than too few. I suggest finding an example of a partitioning that is OK, and one that is not.)

**Comment by daccordeon** [comment]
Thanks! Will search for two blobs close together with nothing else nearby as an OK example.
See #32

**Comment by daccordeon** [comment]
This looks like a candidate for two aligned ellipses:
J121923+054926

Sometimes a blob is large enough to count as multiple sources, this is a not very interesting form of multi-component:
TGSS J153418.0+101644, etc.
NVSS J153418+101544, J153414+101647, J153417+101708, J153417+101821

Also, looked up the most distant radio galaxy (looks very boring):
TGSS J153049.9+104933, NVSS J153050+104931

**Comment by daccordeon** [comment]
Here's one such case of single match partition which seems alright.
TGSS J104025.2-162920, NVSS J104025-162920
Why it hasn't jumped to the nearby blobs, I don't know, but I would agree with the label.

**Comment by daccordeon** [comment]
Move to close this and issue #32
