### ISSUE TITLE
Find multi-component objects in NVSS and TGSS

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#32]
Using #31

**Comment by daccordeon** [comment]
And look at them in cut-outs

**Comment by MatthewJA** [comment]
http://tgssadr.strw.leidenuniv.nl/hips/

**Comment by MatthewJA** [comment]
@daccordeon Can you put a few pictures of "multi-component" objects into your report? reminiscent of #36.

No worries if you don't get time though

**Comment by daccordeon** [comment]
See comment in issue #31 , the best I've currently got are two blobs right next to each other, will keep might keep searching for something that looks convincing due to something other than separation.

**Comment by MatthewJA** [comment]
I'll leave this open for you then.

**Comment by daccordeon** [comment]
See comment in #31 for blob examples.
