### ISSUE TITLE
Give Matthew some pairs to label

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/blobmatch#35]
As a CSV file with TGSS, NVSS columns.

**Comment by daccordeon** [comment]
TGSSADR J101034.2-180048,NVSS J101037-180004
TGSSADR J105333.2-292336,NVSS J105333-292335
TGSSADR J105054.6-252718,NVSS J105130-252902
TGSSADR J105006.5-183816,NVSS J105006-183816
TGSSADR J101329.4-283116,NVSS J101408-282642
TGSSADR J104210.6-213657,NVSS J104146-213846
TGSSADR J104638.2-323505,NVSS J104600-323801
TGSSADR J104202.6-164853,NVSS J104202-164851
TGSSADR J105843.0-241234,NVSS J105843-241236
TGSSADR J100012.2-272336,NVSS J100012-272341
TGSSADR J101201.3-310740,NVSS J101201-310740
TGSSADR J100431.3-233806,NVSS J100431-233804
TGSSADR J103459.1-254453,NVSS J103459-254453
TGSSADR J100834.6-260513,NVSS J100842-260224
TGSSADR J105820.2-270521,NVSS J105820-270519
TGSSADR J103548.0-295420,NVSS J103548-295418
TGSSADR J100924.5-303939,NVSS J100857-303155
TGSSADR J110903.9-212221,NVSS J110904-212226
TGSSADR J105326.3-323410,NVSS J105327-324346
TGSSADR J104841.8-241638,NVSS J104901-241048
TGSSADR J101043.1-153803,NVSS J101047-153731
TGSSADR J101241.5-283607,NVSS J101240-283607
TGSSADR J110914.9-174210,NVSS J110914-174211
TGSSADR J111448.3-285057,NVSS J111448-285055
TGSSADR J111410.0-324039,NVSS J111410-324035
TGSSADR J104232.8-281149,NVSS J104246-282034
TGSSADR J103012.1-255717,NVSS J103012-255712
TGSSADR J101900.5-263947,NVSS J101900-263949
TGSSADR J095937.2-341859,NVSS J095934-341648
TGSSADR J101306.6-164122,NVSS J101306-164122
TGSSADR J110956.0-280847,NVSS J110949-280929
TGSSADR J101419.7-280026,NVSS J101419-280028
TGSSADR J105934.4-251605,NVSS J105959-251551
TGSSADR J105905.2-270519,NVSS J105905-270521
TGSSADR J111010.5-283731,NVSS J111015-283743
TGSSADR J103645.2-312354,NVSS J103656-311502
TGSSADR J103902.1-161248,NVSS J103902-161248
TGSSADR J110845.0-201411,NVSS J110811-200831
TGSSADR J103423.3-153431,NVSS J103427-153407
TGSSADR J110211.6-180441,NVSS J110220-175926

**Comment by daccordeon** [comment]
That's 40 above, just do however many (I only ask for the first 20, I'll do the second 20). From manual_labels.csv in push (to be filled in).

**Comment by MatthewJA** [comment]
Here you go. I added some columns. Whether two components are the same source (physical object), whether the two components are the same object between surveys, and comments.
[manual_labels.txt](https://github.com/MatthewJA/blobmatch/files/3724554/manual_labels.txt)

**Comment by daccordeon** [comment]
I don't understand the difference between the two y/n columns, will discuss.
